# @Author Reece Cosbey
# @File Name makefile
# @date 2024-09-20
# @brief makefile for compiling the program

CC = g++
TARGET = employee
CFLAGS = -c -Wall -Wextra

all: $(TARGET)

$(TARGET): main.o Employee.o Officer.o Supervisor.o
	$(CC) $^ -o $@

main.o: main.cpp
	$(CC) $(CFLAGS) $< -o $@

Employee.o: Employee.cpp
	$(CC) $(CFLAGS) $< -o $@

Officer.o: Officer.cpp
	$(CC) $(CFLAGS) $< -o $@

Supervisor.o: Supervisor.cpp
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f *.o *~ $(TARGET)
